version: '2'
services:
    smartstatement-app:
        image: smartstatement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartstatement-mysql:3306/smartstatement?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=smartstatement-elasticsearch:9300
        ports:
            - 8080:8080
    smartstatement-mysql:
        extends:
            file: mysql.yml
            service: smartstatement-mysql
    smartstatement-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smartstatement-elasticsearch
